version: 0.0
os: linux
files:
  - source: Demo1.0.sh
  destination: /home/ubuntu
hooks:
  AfterInstall:
    - location: after_script.sh
      timeout: 180
  ApplicationStart:
      timeout: 100 
      
